name: mightydelivery_admin_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # BASE
  intl: ^0.19.0
  html: ^0.15.4
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  month_year_picker: ^0.4.0+1

  # CONNECTIVITY
  http: ^1.2.2
  connectivity_plus: ^6.0.5

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # TOAST
  fluttertoast: ^8.2.8

  # IMAGE
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2


  # UI
  lottie: ^3.1.2
  syncfusion_flutter_charts: ^23.2.6
  flutter_switch: ^0.3.2

  # COUNTRY
  country_code_picker: ^3.0.0

  # PACKAGE INFO
  package_info_plus: ^8.0.2

  # LUNCH URL
  url_launcher: ^6.3.0

  # LAUNCH GOOGLE MAP
  maps_launcher: ^2.2.1
  google_maps_place_picker_mb: ^3.1.2
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.1

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.2.0
  firebase_database: ^11.1.1
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^5.4.0
  file_picker: ^8.0.0+1


  # TIMELINE
  timeline_tile: ^2.0.0

  line_icons: ^2.0.3

  # DATETIME PICKER
  date_time_picker: ^2.1.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.4

  # CURRENCY PICKER
  currency_picker: ^2.0.21

  # READ MORE LESS
  readmore: ^3.0.0

  # DOWNLOAD INVOICE PDF
  #  pdf: ^3.10.6
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  path_provider: ^2.1.4
  open_file: ^3.5.3
  dropdown_button2: ^2.3.9

  #CIRCULAR PROGRESS BAR
  percent_indicator: ^4.2.3


  #multiple_selection:
  multi_select_flutter: ^4.1.3
  multi_dropdown: ^3.0.1

  html_editor_enhanced: ^2.6.0
  permission_handler: ^11.3.1
  chewie: ^1.8.2
  video_player: ^2.9.1


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  mobx_codegen: ^2.6.1

  #flutter packages pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  intl: 0.18.0
  http: ^0.13.0
  connectivity_plus: ^3.0.3
  freezed_annotation: ^2.4.1
  cloud_firestore: ^5.0.0
  package_info_plus: ^4.0.2
  firebase_core:


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/flag/
    - assets/packing_symbols/

